# yamllint disable rule:line-length
# This file is rendered via JSON-e by
# - github events - https://github.com/taskcluster/taskcluster/tree/main/services/github
# - cron tasks - https://hg.mozilla.org/ci/ci-admin/file/default/build-decision/
# - action tasks - taskcluster/taskgraph/actions/registry.py
---
version: 1
reporting: checks-v1
autoCancelPreviousChecks: true
policy:
    allowComments: collaborators
    pullRequests: public
messages:
    - topic: decision
      context:
         trustDomain: mozilla
         level: 1
